<a href="https://colab.research.google.com/github/SaiJeevan25/ML_Practice/blob/main/ML_23_07_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = [
    ['A','Apple'],
    ['B','Ball'],
    ['C','Cat']
  ]

a = pd.DataFrame(data, index=['1', '2', '3'], columns=['Alphabet', 'Words'])

  Alphabet  Words
1        A  Apple
2        B   Ball
3        C    Cat


In [ ]:
import pandas as pd

data = [
    [100.5, 12000, 20000, 50000],
    [150.8, 18000, 50000, 60000],
    [200.9, 22000, 70000, 70000],
    [30000, 30000, 100000, 80000],
    [40000, 45000, 125000, 90000]
]

index = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']
cols = [2014,2015,2016,2017]

a = pd.DataFrame(data, index=index, columns=cols)

print(a)

print()
#Row labels
print(a.index)

print()
#column labels
print(a.columns)

print()
#Dtypes for columns
print("Dtypes: \n", a.dtypes)

#Dimensions
print("\nDimensions: ", a.ndim)

#Shape
print('\nShape: ', a.shape)

#Size
print('\nSize: ', a.size)

#values
print('\nValues: \n', a.values)

#last 2 rows
print()
print(a.tail(2))

print()
#first 2 cols
print(a.iloc[:3:2])

#Check Empty
print("\nIs Empty: ", a.empty)


            2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000

Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')

Index([2014, 2015, 2016, 2017], dtype='int64')

Dtypes: 
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object

Dimensions:  2

Shape:  (5, 4)

Size:  20

Values: 
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]

           2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000

          2014   2015   2016   2017
Madhu    100.5  12000  20000  50000
Kinshuk  200.9  22000  70000  70000

Is Empty:  False


In [ ]:
data2 = {
    '2018': {
        'Madhu': 160000,
        'Kusum': 110000,
        'Kinshuk': 500000,
        'Ankit': 340000,
        'Shruti': 900000
    }
}
sales2 = pd.DataFrame(data2)


a = pd.concat([a, sales2], axis= 1)
print(a)

#transpose
print("\nTranspose: \n", a.T)

            2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000

Transpose: 
          Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0


In [ ]:
#2017
print("Sales 2017: \n", a[2017])

print(a.loc[['Madhu', 'Ankit'], [2017, '2018']])
print()
print(a.loc['Shruti', 2016])
print()
a.loc['Sumeet'] = [196.2, 37800, 52000, 78438, 38852, None]  # fill 2018 later
a.at['Sumeet', '2018'] = 38852


Sales 2017: 
 Madhu      50000
Kusum      60000
Kinshuk    70000
Ankit      80000
Shruti     90000
Name: 2017, dtype: int64
        2017    2018
Madhu  50000  160000
Ankit  80000  340000

125000


In [ ]:
a.drop(columns=2014, inplace=True)

In [ ]:
a.drop(index='Kinshuk', inplace=True)

In [ ]:
a.rename(index={'Ankit': 'Vivaan', 'Madhu': 'Shailesh'}, inplace=True)

In [ ]:
a.at['Shailesh', '2018'] = 100000

In [ ]:
a.to_csv('SalesFigures.csv', index=False, header=False)

In [ ]:
# Read raw data
SalesRetrieved = pd.read_csv('SalesFigures.csv', header=None)

# Assign same row/column labels as Sales
SalesRetrieved.index = a.index
SalesRetrieved.columns = a.columns

print(SalesRetrieved)


           2015    2016   2017    2018
Shailesh  12000   20000  50000  100000
Kusum     18000   50000  60000  110000
Vivaan    30000  100000  80000  340000
Shruti    45000  125000  90000  900000


In [ ]:
import pandas as pd

data = {
    'Item': ['TV', 'TV', 'TV', 'AC'],
    'Company': ['LG', 'VIDEOCON', 'LG', 'SONY'],
    'Rupees': [12000, 10000, 15000, 14000],
    'USD': [700, 650, 800, 750]
}

df = pd.DataFrame(data)
print(df)


  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750


In [ ]:
new_data = [
    {'Item': 'TV', 'Company': 'SAMSUNG', 'Rupees': 17000, 'USD': 900},
    {'Item': 'AC', 'Company': 'LG', 'Rupees': 16000, 'USD': 850}
]

df = pd.concat([df, pd.DataFrame(new_data)], ignore_index=True)

In [ ]:
lg_tv_max = df[(df['Company'] == 'LG') & (df['Item'] == 'TV')]['Rupees'].max()
print("Maximum price of LG TV:", lg_tv_max)

Maximum price of LG TV: 15000


In [ ]:
total_rupees = df['Rupees'].sum()
print("Total sum of all products (Rupees):", total_rupees)

median_sony_usd = df[df['Company'] == 'SONY']['USD'].median()
print("Median USD of SONY products:", median_sony_usd)

df_sorted = df.sort_values(by='Rupees')
print("Sorted DataFrame by Rupees:")
print(df_sorted)

Total sum of all products (Rupees): 84000
Median USD of SONY products: 750.0
Sorted DataFrame by Rupees:
  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC        LG   16000  850
4   TV   SAMSUNG   17000  900


In [ ]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Aparna', 'Pankaj', 'Ram', 'Ramesh', 'Naveen', 'Krishnav', 'Bhawna'],
    'Degree': ['MBA', 'BCA', 'M.Tech', 'MBA', np.nan, 'BCA', 'MBA'],
    'Score': [90.0, np.nan, 80.0, 98.0, 97.0, 78.0, 89.0]
}

df = pd.DataFrame(data)

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Aparna', 'Pankaj', 'Ram', 'Ramesh', 'Naveen', 'Krishnav', 'Bhawna'],
    'Degree': ['MBA', 'BCA', 'M.Tech', 'MBA', np.nan, 'BCA', 'MBA'],
    'Score': [90.0, np.nan, 80.0, 98.0, 97.0, 78.0, 89.0]
}

df = pd.DataFrame(data)
print(df)

       Name  Degree  Score
0    Aparna     MBA   90.0
1    Pankaj     BCA    NaN
2       Ram  M.Tech   80.0
3    Ramesh     MBA   98.0
4    Naveen     NaN   97.0
5  Krishnav     BCA   78.0
6    Bhawna     MBA   89.0


In [ ]:
print(df.groupby('Degree')['Score'].max())

df['Score'].fillna(76, inplace=True)
df['Degree'].fillna('76', inplace=True)  # or any other default string if 76 is confusing


Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
Name: Score, dtype: float64


/tmp/ipython-input-21-3845681774.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Score'].fillna(76, inplace=True)
/tmp/ipython-input-21-3845681774.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'd

In [ ]:
df.set_index('Name', inplace=True)


KeyError: "None of ['Name'] are in the columns"

In [ ]:
print(df)
print()
print(df.groupby(['Name', 'Degree'])['Score'].mean())
print()
mba_count = df[df['Degree'] == 'MBA'].shape[0]
print("Number of MBA students:", mba_count)
print()
bca_mode = df[df['Degree'] == 'BCA']['Score'].mode()
print("Mode marks of BCA students:", bca_mode.values)


          Degree  Score
Name                   
Aparna       MBA   90.0
Pankaj       BCA   76.0
Ram       M.Tech   80.0
Ramesh       MBA   98.0
Naveen        76   97.0
Krishnav     BCA   78.0
Bhawna       MBA   89.0

Name      Degree
Aparna    MBA       90.0
Bhawna    MBA       89.0
Krishnav  BCA       78.0
Naveen    76        97.0
Pankaj    BCA       76.0
Ram       M.Tech    80.0
Ramesh    MBA       98.0
Name: Score, dtype: float64

Number of MBA students: 3

Mode marks of BCA students: [76. 78.]
